# Programming Assignment 6
---
**Author:** Dylan Tulett  
**Version:** 1.0  
**Semester:** Fall 2020  

This *notebook* contains my solution to **Programming Assignment 6**

- Problem 1: Create a 2,2 array of 10,20,30,40 and perform several operations on the whole array.
- Problem 2: Create 2 3,3 arrays and multiply them together.
- Problem 3: Load 5 files and compile them into one array. Then calculate the mean of each column. 

In [105]:
import numpy as np
import statistics as stats

## Part 1

In [45]:
a1 = np.array([[10,20],[30,40]])

In [46]:
a1 **= 2
print(a1)

[[ 100  400]
 [ 900 1600]]


In [47]:
a1 += 100
print(a1)

[[ 200  500]
 [1000 1700]]


In [48]:
a1 *= 5
print(a1)

[[1000 2500]
 [5000 8500]]


In [49]:
a1 = np.sqrt(a1)
print(a1)

[[31.6227766  50.        ]
 [70.71067812 92.19544457]]


## Part 2

In [54]:
b1 = np.array(np.arange(3,28,3)).reshape(3,3)

In [51]:
b2 = np.linspace(10,20,9).reshape(3,3)

In [55]:
b2

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [53]:
b3 = b1 * b2
print(b3)

[[ 30.   67.5 112.5]
 [165.  225.  292.5]
 [367.5 450.  540. ]]


## Part 3

In [66]:
c1 = np.vstack(((np.load('process1.npy')),
                (np.load('process2.npy')),
                (np.load('process3.npy')),
                (np.load('process4.npy')),
                (np.load('process5.npy'))))

In [65]:
c1

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)

In [102]:
def column_mean(data,col_num):
    column = []
    for row in range(len(data)):
        column.append(data[row,col_num])
    mean = stats.fmean(column)
    return mean

In [103]:
column0 = column_mean(c1,0)
column1 = column_mean(c1,1)
column2 = column_mean(c1,2)
column3 = column_mean(c1,3)
column4 = column_mean(c1,4)

In [104]:
print(f'The means of each column, from left to right, are {column0}, {column1}, {column2}, {column3}, {column4}.')

The means of each column, from left to right, are 72.0, 27.8, 45.6, 12.0, 47.8.
